# Cadastro de dados #
saudação = ("Olá")
print("Olá,")
inicio = input("Digite: ok e tecle enter para continuar: ")
print("Perfeito, agora vamos coletar alguns dados!")
nome = input("Digite seu nome: ")
print("seja bem vindo! " + nome)
idade = input("digite sua idade: ")
altura = input("digite sua altura: ")
peso = input("digite seu peso: ")
input("confirme seus dados abaixo, digite ok e pressione enter para continuar: ")
print(nome)
print(idade)
print(altura+"cm")
print(peso+"KG")
input("para confirmar digite ok: ")
print("Seus dados foram registrados com sucesso, obrigado!")
print("Fim de código!")
